creación user y coach
saradvr/fitnessmatch-backend pull request #2
Opened 2021-03-15 22:55 UTC by saradvr

# Creación de modelo, controlador y rutas de Usuario y Coach

User Sign Up: Esto crea el usuario y también el coach al poner userType: Coach
![createUser](https://user-images.githubusercontent.com/75816184/111231435-451d7580-85b7-11eb-981b-8db3b34ae39c.gif)

User Login
![loginUser](https://user-images.githubusercontent.com/75816184/111231451-4ea6dd80-85b7-11eb-9125-8dac63a5c663.gif)

Listado de coaches
![listCoaches](https://user-images.githubusercontent.com/75816184/111231507-69795200-85b7-11eb-8bc6-45129a367006.gif)

Actualización coach
![updateCoach](https://user-images.githubusercontent.com/75816184/111231540-74cc7d80-85b7-11eb-81cd-154ac002a096.gif)

2021-03-15 23:51 UTC, Otho01 submitted a review, later dismissed

2021-03-16 00:18 UTC, SrTeoria approved these changes, later dismissed

2021-03-16 13:01 UTC, simonhoyos requested changes

2021-03-16 13:01 UTC, simonhoyos commented on src/controllers/coach.controller.js
> +      await coach.save({ validateBeforeSave: false })
El método findByIdAndUpdate guarda los cambios en la base de datos. No es necesario ejecutar el save

2021-03-16 13:01 UTC, simonhoyos commented on src/controllers/coach.controller.js
> +      await coach.save({ validateBeforeSave: false })
El método save se debe ejecutar cuando haces cambios directamente en el documento. Ejemplo: `coach.name = 'Maria'`

2021-03-16 13:01 UTC, simonhoyos commented on src/controllers/user.controller.js
> +const bcrypt = require('bcrypt')
Ojo con la identación de este archivo. En otros archivos estan usando espacios y en este se usan tabs. Adicionalmente hay lugares donde hay tabs adicionales

2021-03-16 13:01 UTC, simonhoyos commented on src/models/user.model.js
> +const { model, models, Schema } = require('mongoose')
también hay que revisar la identación de este archivo

2021-03-16 13:01 UTC, simonhoyos commented on src/server.js
> +app.get('/', auth, (req, res) => {
Está ruta sobra, no es necesaria para la aplicación. Era el ejemplo de clase para mostrarles como funcionaba la autenticación

2021-03-16 16:09 UTC, SrTeoria approved these changes

2021-03-16 16:09 UTC, Pethofreed approved these changes

2021-03-16 16:10 UTC, simonhoyos approved these changes

2021-03-16 16:23 UTC, merged