TVC-46 Y TVC-47
saradvr/fitnessmatch-backend pull request #4
Opened 2021-03-19 01:55 UTC by SrTeoria

Se hizo los modelos, controladores y rutas para las entidades de especializaciones y disciplinas. Además se integro con las entidades de cliente y entrenador.
![TVC46Y47](https://user-images.githubusercontent.com/71355960/111720582-2e338900-882c-11eb-888b-8b5e83112bd6.gif)

2021-03-19 02:44 UTC, Otho01 submitted a review, later dismissed

2021-03-19 12:59 UTC, simonhoyos requested changes

2021-03-19 12:59 UTC, simonhoyos commented on src/controllers/client.controller.js
> +      }
Ahora hacemos una llamada y revisamos esta lógica

2021-03-19 12:59 UTC, simonhoyos commented on src/controllers/coach.controller.js
> +      }
Lo mismo que el comment anterior

2021-03-19 12:59 UTC, simonhoyos commented on src/models/coach.model.js
> +    type: [{ type: Schema.Types.ObjectId,
Ojo con la identación agrega un salto de línea para que quede alineado

2021-03-19 23:58 UTC, saradvr approved these changes

2021-03-19 23:59 UTC, Otho01 approved these changes

2021-03-20 00:21 UTC, simonhoyos approved these changes
Me gusta como quedo la función

2021-03-23 04:19 UTC, merged